from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CalculatePost200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None):  # noqa: E501
        """CalculatePost200Response - a model defined in OpenAPI

        :param result: The result of this CalculatePost200Response.  # noqa: E501
        :type result: float
        """
        self.openapi_types = {
            'result': float
        }

        self.attribute_map = {
            'result': 'result'
        }

        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'CalculatePost200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _calculate_post_200_response of this CalculatePost200Response.  # noqa: E501
        :rtype: CalculatePost200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> float:
        """Gets the result of this CalculatePost200Response.


        :return: The result of this CalculatePost200Response.
        :rtype: float
        """
        return self._result

    @result.setter
    def result(self, result: float):
        """Sets the result of this CalculatePost200Response.


        :param result: The result of this CalculatePost200Response.
        :type result: float
        """

        self._result = result
