from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CalculatePostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, num1=None, num2=None):  # noqa: E501
        """CalculatePostRequest - a model defined in OpenAPI

        :param num1: The num1 of this CalculatePostRequest.  # noqa: E501
        :type num1: float
        :param num2: The num2 of this CalculatePostRequest.  # noqa: E501
        :type num2: float
        """
        self.openapi_types = {
            'num1': float,
            'num2': float
        }

        self.attribute_map = {
            'num1': 'num1',
            'num2': 'num2'
        }

        self._num1 = num1
        self._num2 = num2

    @classmethod
    def from_dict(cls, dikt) -> 'CalculatePostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _calculate_post_request of this CalculatePostRequest.  # noqa: E501
        :rtype: CalculatePostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def num1(self) -> float:
        """Gets the num1 of this CalculatePostRequest.


        :return: The num1 of this CalculatePostRequest.
        :rtype: float
        """
        return self._num1

    @num1.setter
    def num1(self, num1: float):
        """Sets the num1 of this CalculatePostRequest.


        :param num1: The num1 of this CalculatePostRequest.
        :type num1: float
        """

        self._num1 = num1

    @property
    def num2(self) -> float:
        """Gets the num2 of this CalculatePostRequest.


        :return: The num2 of this CalculatePostRequest.
        :rtype: float
        """
        return self._num2

    @num2.setter
    def num2(self, num2: float):
        """Sets the num2 of this CalculatePostRequest.


        :param num2: The num2 of this CalculatePostRequest.
        :type num2: float
        """

        self._num2 = num2
