services:
  flask:
    build: ./backend
    container_name: flask_server
    ports:
      - "8080:8080"

  nginx:
    build: ./frontend
    container_name: nginx_server
    ports:
      - "5000:80"
    depends_on:
      - flask
